apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: ocr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ocr
  template:
    metadata:
      namespace: chunkmydocs
      labels:
        app.kubernetes.io/name: ocr
    spec:
      containers:
      - name: ocr
        image: luminainc/ocr:95e07f51
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: chunkmydocs-secrets
        env:
        - name: PG__POOL__MAX_SIZE
          value: "3"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
