_target_: src.datamodule.Synthtabnet
root_dir: ../../../../DATASETS/synthtabnet/marketing
label_type: ${dataset.label_type}
split: train
json_html: clean_html_synthetic_data.jsonl
transform: ${dataset.augmentation}
cell_limit: ${dataset.cell_limit}