apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    {{- include "chunkr.labels" . | nindent 4 }}
data:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_PROXY: "edge"
  KC_HOSTNAME: "{{ .Values.services.auth.ingress.subdomain }}.{{ .Values.ingress.domain }}"
  KC_FEATURES: "hostname:v2"
  KC_HOSTNAME_DEBUG: "true"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://{{- .Release.Name }}-postgres:5432/keycloak"
  KC_DB_USERNAME: "{{ .Values.services.postgres.credentials.username }}"
  KC_DB_PASSWORD: "{{ .Values.services.postgres.credentials.password }}" 